/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_LanceReader */

#ifndef _Included_com_example_LanceReader
#define _Included_com_example_LanceReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_LanceReader
 * Method:    readRangeJni
 * Signature: (Ljava/lang/String;II)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_example_LanceReader_readRangeJni
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_example_LanceReader
 * Method:    readIndexJni
 * Signature: (Ljava/lang/String;[I)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_example_LanceReader_readIndexJni
  (JNIEnv *, jclass, jstring, jintArray);

#ifdef __cplusplus
}
#endif
#endif
