/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_LanceWriter */

#ifndef _Included_com_example_LanceWriter
#define _Included_com_example_LanceWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_LanceWriter
 * Method:    write
 * Signature: (Ljava/lang/String;Lorg/apache/arrow/vector/ipc/message/ArrowRecordBatch;)V
 */
JNIEXPORT void JNICALL Java_com_example_LanceWriter_write
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
